### DISCUSSION TITLE
Use `eos-analysis` to run tasks in a repeatable/reproducible way

### DISCUSSION THREAD

**Discussion by dvandyk** [eos/eos#432] [Ideas]
Meril and I just discussed how to record the parameters for the individual tasks that one carries out using `eos-analysis`.
Here's a mockup of how to record this inside the analysis file:

```YAML
steps:
  - name: Optimize
    tasks:
      - name: MCMC prerun for CKM-all to prepare optimization
        task: sample-mcmc
        parameters:
          posterior: 'CKM-all'
          pre_N: 1000

      - name: Optimization
        task: find-mode
        parameters:
          posterior: 'CKM-all'


  - name: Sample
    configuration:
      [
          { posterior: CKM-pi                                                          },
          { posterior: CKM-rho, 'sample-mcmc': { pre_N: 1500, starting_point: 'mode' } }
      ]
    tasks:
      - name: MCMC prerun for {{ posterior }} to prepare sampling
        task: sample-mcmc
        parameters:
          posterior: {{ posterior }} # is the default
          pre_N: 1000 # overriden for 'CKM-rho' to use 'pre_N': 1500

      - name: Determine the clusters for {{ posterior }}
        task: find-clusters
        parameters:
          posterior: {{ posterior }} # is the default
```

This would run two steps:
 1. `Optimize`, which only uses a single posterior,
 2. `Sample`, which is carried out for two posteriors: `CKM-pi` and `CKM-rho`. Note that `CKM-rho` is meant to override some parameters in the step's first task (`sample-mcmc`).

Looking for feedback! @tblake00 @DomLeljak @pluegh @SKuerten @greenwald
