### ISSUE TITLE
Validation needs improvement

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#1030]
I can define a mask that depends on a non-existent parameter, e.g.
```yaml
masks:
  - name: test
    description:
      - name: 0->Kpi::test
        expression: '[[fake::parameter]]'
```
and this does not get caught by our current validation, only throwing an error when the mask is created
