### ISSUE TITLE
Organize parameters in sections and groups

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#165]
I have managed to create sections and groups for the built-in observables. It would be nice if we could achieve the same for the default parameters. I think the most straight-forward modification would probably be to create one parameter YAML file per section, with a the following structure:

``` YAML
title: 'A Section title that allows \LaTeX notation'
description: 'Description for the entire section, allowing \LaTeX notation.'
groups:
  - title: 'A first group title that allows \LaTeX notation'
    description: 'Descriptions for this specific group, allowing \LaTeX notation.'
    parameters:
      'mass::X@Example':
        central: +1.0
        min: +0.5
        max: +1.5
        unit: 'GeV'
        latex: '$M_X$'
        comment: 'The mass of the unmotivated X particle'
...
```
We should also re-indent, with indenting by 2 spaces per level.

Would love to have some feedback @cBobeth @gubernari @SKuerten
