### ISSUE TITLE
Add eos-analysis script

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#212]
Following the discussion today, we want to represent any statistical analysis in terms of its likelihood and its prior. To avoid re-writing identical likelihoods we agreed to use the following YAML representation:

```
likelihoods:
  - name: leptonic-afb
    constraints:
      - Lambda_b->Lambdamu^+mu^-::A_FB^l[15.0,20.0]@LHCb-2015B
  - name: hadronic-afb
    constraints:
      - Lambda_b->Lambdamu^+mu^-::A_FB^h[15.0,20.0]@LHCb-2015B

priors:
  - name: SM
    parameters: []
  - name: c9
    parameters:
      - parameter: b->smumu::Re{c9}
        min: 1.0
        max: 7.0
        type: uniform

posteriors:
  - name: all-SM
    likelihood:
      - leptonic-afb
      - hadronic-afb
    prior:
      - SM
```

A basic ```eos-analysis``` script would feature three sub commands:
 - ```list-likelihoods```
 - ```list-priors```
 - ```list-posteriors```
