### ISSUE TITLE
More efficient way to define a large number, a vector or a matrix of parameters

### ISSUE THREAD

**Issue by mreboud** [eos/eos#291]
Entering a large number of parameters (e.g. the coefficients of a parametrization) is currently quite error-prone and makes the parameters files difficult to read and debug. It would be interesting to have a more elegant way to enter large number of parameters.

One possibility would be to enable templating of parameters, using some sort of format string that is filled by the C++ parser side.

**Comment by mreboud** [comment]
@dvandyk suggests the following yaml implementation
```test::parameter_{{n}}^{{process}}:
    central: 0.0
    min: -1.0
    max: +1.0
    matrix:
        n: [0, 1, 2, 3, 4, 5]
        process: ['B->D^*lnu', 'B->Kll']
```

**Comment by mreboud** [comment]
This rises a couple of issues:
 1. std::format needs C++20 or higher;
 2. std::format replacement fields can be `{}` or `{n}` with n a non-negative number. This means that the above implementation needs to be changed;
 3. `{{` needs to be use for `{` in formatted names
 4. the latex representation is problematic since the the name substitutions don't necessarily correspond to the latex ones...


Item 1. will be fixed by the use of gcc-10 that supports C++20. For item 2. we can use the following implementation
```
test::parameter_{0}^{1}:
    central: 0.0
    min: -1.0
    max: +1.0
    matrix:
        - [0, 1, 2, 3, 4, 5]
        - ['B->D^*lnu', 'B->Kll']
```
Item 3 is not really a problem I think, this only impacts templated parameters. For item 4 I don't know, the best would be to have the possibility to give the latex representation of the replacements in the replacement matrix, but it starts to be a bit involved...

**Comment by mreboud** [comment]
It appears that no compiler support std::format for the moment so I used [boost/format](https://www.boost.org/doc/libs/1_75_0/libs/format/doc/format.html). It implies a different syntax, unfortunately not compatible with python's string formatting:
```
      'test::parameter_%1%^%2%':
          central: 0.0
          min: -1.0
          max: +1.0
          matrix:
              - [0, 1, 2, 3, 4, 5]
              - ['B->D^*lnu', 'B->Kll']
```
I have a first commit that works on [this branch](https://github.com/mreboud/eos/tree/param_templating).
Unfortunately, boost/format is not compatible with C++20 yet, and I had to use C++14 for the moment. This compatibility is supposed to be solved now, cf [this issue](https://github.com/boostorg/format/issues/73), but I couldn't get it to work.
