### ISSUE TITLE
[python] Deserialization of manual constraints

### ISSUE THREAD

**Issue by mreboud** [eos/eos#310]
When entering a manual constraint for an eos.analysis, the deserialization sometimes crashes due to a type problem:
```
manual_constraints_ = {
        'B->K^*::re_ratio_perp7': {
            'type': 'Gaussian',
            [...]
            'mean': 0.0003123333428265962,
            [...]
        }
}
```
works as expected, but
```
mean = np.array([0.0003123333428265962])
manual_constraints = {
        'B->K^*::re_ratio_perp7': {
            'type': 'Gaussian',
            [...]
            'mean': mean[0],
            [...]
        }
}
```
crashes with a yaml-cpp error.

The problem is due to the difference in types `type(mean[0]) = numpy.float64` vs. `type(0.0003123333428265962) = float` and can be solved by casting: `np.float(mean[0])`.

Question: What is the problem with numpy types? Should we enforce this casting?

**Comment by mreboud** [comment]
Thanks @pluegh for the work around.

**Comment by mreboud** [comment]
This is more complex that it may look. The yaml output of a Numpy array looks weird: in the above example, the yaml string of the mean will be
```
mean: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  oS/eC6OLwz4=
```
instead of the expected `mean: 2.33e-06`. This output is not supported by yaml.cpp which causes the error.

I suggest that we enforce `float` type by reading the constraint dictionary before we dump it, i.e. here https://github.com/eos/eos/blob/d10f33ea1120701a47a8cfc83d57de31ed568e9d/python/eos/analysis.py#L138. @dvandyk what do you think?
