### ISSUE TITLE
Add support for mixture densities as part of the log-likelihood

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#338]
This will enable to use the output of a PMC fit in case of large final perplexity (> ~90%).

Steps:
 - in ``eos/statistics/log-likelihood.hh``
     - [ ] document ``LogLikelihood::Mixture``
 - in ``eos/statistics/log-likelihood.cc``
     - [ ] fix computation of ``MixtureBlock::number_of_observations()``: this should be the number of observations of each component, not their sum!
 - in ``eos/constraint.hh``
     - [ ] add ``MixtureConstraintEntry`` class
     - [ ] (de)serialization should copy MultivariateGaussian as much as possible, but include
``` YAML
type: Mixture
dim: ... # special case for dim = 1
observables: [...] # as in MultivariateGaussian(Covariance)
weights: [....] # normalized to 1
components:
    - type: MultivariateGaussian(Covariance)
      means: [...]
      covariance: [...]
    - type: MultivariateGaussian(Covariance)
      means: [...]
      covariance: [...]
```
 - in [``eos/constraint.cc``](https://github.com/eos/eos/blob/9380e13a26cb0967350ac0c1d2e8e3bc347c01bf/eos/constraint.cc#L1637)
    - [ ] register the new ``MixtureConstraintEntry`` for deserialization
