### ISSUE TITLE
`eos.AnalysisFile` silently accepts incorrect file syntax

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#424]
```
likelihoods:
  - name: EXP-rho
    constrains:
      - B^+->rho^0lnu::BR@BPR:2021A
```

is accepted by `eos.AnalysisFile` without any complaints, but the likelihood ``EXP-rho`` will be empty.
The reason is that ``constrains`` is misspelled :angry: 

 - fix this bug
 - audit `eos.AnalysisFile` for similar bugs
