### ISSUE TITLE
Global options supercede local ones in analysis files

### ISSUE THREAD

**Issue by mreboud** [eos/eos#648]
Two issues:
 - [ ] ~When postdicting observables, the options specified in the ``prediction`` item of an analysis file should override the global options and not the other way around.~
 - [x] Log error message when a user provides local options in a ``predictions`` item that are overridden by the posterior's global options
 - [x] They currently seem to be erased when saving the prediction file.

**Comment by dvandyk** [comment]
The behaviour is actually as expected. A posterior's global options supercede the options specific to an individual observable. I would leave the behaviour as is and fix the analysis file instead. In our case, we have:
```YAML
likelihoods:
  - name: EXP-pi
    constraints:
      - 'B^0->pi^-l^+nu::BR@HFLAV:2019A;form-factors=BCL2008-4'

posteriors:
  - name: CKM-all
    global_options:
      l: e
    ...
    likelihood:
      - EXP-pi

predictions:
  - name: leptonic-BR-CKM
    global_options:
      model: CKM
    observables:
      - name: B_u->lnu::BR;l=e
      - name: B_u->lnu::BR;l=mu
      - name: B_u->lnu::BR;l=tau
```

We should have:
```YAML
likelihoods:
  - name: EXP-pi
    constraints:
      - 'B^0->pi^-l^+nu::BR@HFLAV:2019A;form-factors=BCL2008-4;l=e'

posteriors:
  - name: CKM-all
    global_options:
      - ...
    likelihood:
      - EXP-pi

predictions:
  - name: leptonic-BR-CKM
    global_options:
      model: CKM
    observables:
      - name: B_u->lnu::BR;l=e
      - name: B_u->lnu::BR;l=mu
      - name: B_u->lnu::BR;l=tau
```
