### ISSUE TITLE
Allow for a list of kinematic specifications in the predictions part of an analysis file

### ISSUE THREAD

**Issue by mreboud** [eos/eos#673]
I suggest that this should e.g. be a valid syntax:
```
predictions:
  - name: form-factors
    observables:
      - name: B->K^*::V(q2)
        kinematics:
          [ {q2: -15}, {q2: -10}, {q2: -5}, {q2: 0}, {q2: 5} ]
```
