### ISSUE TITLE
Add means to alias or modify parameters in an analysis file

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#801]
use cases:
- modify the LaTeX representation of a parameter, e.g., $\mathcal{C}^{ube\nu_e}_{V_L} \to \mathcal{C}^{ub\ell\nu_\ell}$
```yaml
parameters:
  ubenue::Re{cVL}:
    # only provide keys that should be modified, e.g. here: the latex key
    latex: \mathcal{C}^{ub\ell\nu_\ell}
    # implicitly keep all other keys as they are
```
- alias one parameter to another, e.g., let all users of ``ubmunumu::Re{cVL}`` actually use ``ublnul::Re{cVL}``
  - this can probably be done by redirecting the ``Parameter::Id`` based lookup table
  - suggestions for syntax
```yaml
parameters:
  # suggestion 1: "aliased: alias"
  'ubmunumu::\(.*\)': 'ubenue::\1'
  # suggestion 2: "aliased: { alias: 'alias' }"
  ubmunumu::Re{cVR}:
    alias: ubenue::Re{cVR}
  # suggestion 3: "new: list of aliased"
  ublnul::Re{cVR}: [ ubenue::Re{cVR}, ubmunumu::Re{cVR}, ... ]
  # suggestion 4: "new: { alias_of: [ 'param::1', 'param::2', ... ], unit: 'GeV', central: 0.0, ... }"
  ublnul::Re{cVR}:
    alias_of: [ 'ubenue::Re{cVR}', 'ubmunumu::Re{cVR}', 'ubtaunutau::Re{cVR}' ]
    unit: '1'
    latex: '$\mathcal{C}^{ub\ell\nu_\ell}_{V_R}$'
```
