### ISSUE TITLE
Support imposing relationships between parameters as part of a prior

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#813]
Requires resolution to issue #793 first.

Add means to impose relations between parameters as part of a prior component of the analysis.

Envisaged syntax
```yaml
parameters:
  ublnu::Re{cV} # vector part of ub current
  ublnu::Re{cA} # axial part of ub current
priors:
  - name: WET
    descriptions:
      - { parameter: 'ublnu::Re{cA}', ... }
    relations: 
      ublnu::Re{cVL}: "0.5 * ([[ublnu::Re{cV}]] - [[ublnu::Re{cA}]])"
      ublnu::Re{cVR}: "0.5 * ([[ublnu::Re{cV}]] + [[ublnu::Re{cA}]])"
```

Possible applications:
  - change of basis of WET coefficients
  - connecting form factor parameters in HQE
