### ISSUE TITLE
Enable specification of ``options`` in a ``PredictionObservableComponent``

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#834]

**Comment by MJKirk** [comment]
I'm guessing this should just take a dict to specify options for an observable, e.g. the following would be the correct valid yaml:
```yaml
predictions:
  - name: B-to-l-nu
    observables:
      - name: B_u->lnu::BR
        options: { l : tau }
      - name: B_u->lnu:BR
        options: { l : mu }
```
?
