### ISSUE TITLE
Can we add a new type of prior to distinguish between two local modes?

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#897]
As an example, take this plot by @smeiser.

![image](https://github.com/user-attachments/assets/f31468f8-275a-4973-aaa7-6378b2a32269)

It would be nice if we could switch between sampling from the blue or from the orange mode by simply modifying our prior, e.g. by specifying a expression observable that return values > 0 for one mode, and <0 for the other.

**Comment by dvandyk** [comment]
Notes from a discussion between @mreboud and me just now:

- The type of modes that @smeiser is interested to isolate are still contained within a rotated and shifted hyperrectangle.
- A rotated and shifted D-dimensional hyperrectangle can be specified in terms of a DxD-dimensional rotation matrix $R$, a D-dimensional shift vector $s$, and the boundary vectors $a$ and $b$:

$$M \times \vec{a} + \vec{s} \leq M \times x + \vec{s} \leq M \times\vec{b} + \vec{s}$$

- If $R$ is truly a rotation matrix, then $\text{det}\,R = 1$ and we do not need to adjust the prior at all. If $R$ also stretches the hyperrectangle, i.e., $\text{det}\,R = 1$, then the computation of the evidence needs to adjust for the change in prior volume.

**Comment by dvandyk** [comment]
An example entry in an analysis file for two params ```qbcu::A`` and ``qbcu::B`` could look like this:
```yaml
priors:
  - name: WET
    descriptions:
      - type: transform
        parameters: ['qbcu::A', 'qbcu::B']
        min: [ -1.0, -0.5 ] 
        max: [ +1.0, +1.5 ]
        transform: [[ 0.707106, 0.707106 ], [-0.707106, 0.707106]]
        shift: [ 0.5, 0.0 ]
```
