### ISSUE TITLE
Unclear error when posterior global options override options in predictions

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#912]
The error you get when evaluating observable predictions, and an option in a posterior overrides something in the prediction section, is somewhat unclear.

I saw this when running `eos-analysis validate` on the example file `b-to-u-l-nu.yaml`, and so it was removed from the context of evaluating a chosen prediction in a chosen posterior:
```
eos-analysis validate -f examples/b-to-u-l-nu.yaml 
✖ Global option l=e overrides option part specification l=mu for observable B_u->lnu::BR;l=mu in prediction leptonic-BR-CKM.
✖ Global option l=e overrides option part specification l=tau for observable B_u->lnu::BR;l=tau in prediction leptonic-BR-CKM.
```
My first instinct was to look at the global options within `predictions`, and say "there's no option 'l=e' in there :thinking:".

(Actually in this case they are right next to each other, so I quickly worked it out, but in a more complicated analysis file this might not be the case)
```yaml
posteriors:
  - name: CKM-pi
    global_options:
      l: e
      model: CKM
    prior:
      - CKM
      - FF-pi
    likelihood:
      - TH-pi
      - EXP-pi

predictions:
  - name: leptonic-BR-CKM
    global_options:
      model: CKM
    observables:
      - name: B_u->lnu::BR;l=e
      - name: B_u->lnu::BR;l=mu
      - name: B_u->lnu::BR;l=tau
```

I think it would be nice to add the posterior to the error message, so it says something like
`✖ Global option l=e overrides option part specification l=mu for observable B_u->lnu::BR;l=mu in prediction leptonic-BR-CKM when using posterior CKM-pi .`
