### ISSUE TITLE
Various issues with new snakemake stuff

### ISSUE THREAD

**Issue by MJKirk** [eos/eos#961]
So far trying to use snakemake for our pion FF project, I have come across the following issues:

- Any `base_directory` specified in the AnalysisFile gets overridden 
https://github.com/eos/eos/blob/3cea9ad265fecaf676b08f643488ab7d779abda5/python/eos/tasks.py#L546-L554
by the arguments of the `run` task, which has a default value of the current directory.
I think swapping the order of the dictionaries would make sense.

- task arguments in the analysis file have to be called their internal names not their CLI option name (e.g. `nlive` rather than `number-of-live-points` or `NLIVE`), which can only be found by looking at the source code.  Better documentation is probably enough to fix this.

- When allowing snakemake to run tasks in parallel, the outputs from dynesty appear simultaneously and overwrite each other (e.g. the progress bar from sample-nested).
It looks like the `print_progress` argument in dynesty can turn this ouput off, so maybe we want to use that when running things from snakemake (or at least when doing things in parallel)?

- Danny changed the `StepComponent` parser class in https://github.com/eos/eos/commit/fdeae95f65f974c75ca59dc4739adbbb3714a181, and now the `AnalysisFile.steps` function doesn't work - this function was introduced in PR #521 as a first attempt at allowing for reproducible analyses, so perhaps could be removed if we think snakemake is the better way going forward.

**Comment by MJKirk** [comment]
From the dev meeting:
If you have multiple similar tasks in a `task`, the code gets repetitive:
```
steps:
  - title: 'Sample from CKM-all posterior'
    id: 'CKM-all.sample'
    depends_on: []
    tasks:
      - task: 'sample-nested'
        arguments:
          posterior: 'CKM-all'
          bound: 'multi'
          nlive: 100
          dlogz: 9.0
          maxiter: 4000
      - task: 'sample-nested'
        arguments:
          posterior: 'CKM-all2'
          bound: 'multi'
          nlive: 100
          dlogz: 9.0
          maxiter: 4000
```
Suggestion is to add `default_arguments` below tasks that are added to all tasks. e.g.
```
steps:
  - title: 'Sample from CKM-all posterior'
    id: 'CKM-all.sample'
    depends_on: []
    tasks:
      - default_arguments:
          bound: 'multi'
          nlive: 100
          dlogz: 9.0
          maxiter: 4000
      - task: 'sample-nested'
        arguments:
          posterior: 'CKM-all'
      - task: 'sample-nested'
        arguments:
          posterior: 'CKM-all2'
```
